version: "2.1"
services:
  plex:
    image: linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/peliculas/plex/config:/config
      - /mnt/peliculas/Peliculas:/movies
      - /mnt/peliculas/plex/Profiles:/usr/lib/plexmediaserver/Resources/Profiles
    restart: unless-stopped
