version: "3"
services:
  web:
    image: nginx
    container_name: nginx
    volumes:
    #  - ./templates:/etc/nginx/templates
      - ./conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=guaya.plex.cl
      - NGINX_PORT=80
    restart: always
