---
version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=guaya #optional
      - PASS=guayita.2021 #optional
      - WHITELIST=*.*.*.* #optional
        #      - HOST_WHITELIST=#optional
    volumes:
      - ./config:/config
      - /mnt/peliculas/Peliculas/downloads:/downloads
      - ./watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
